# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ee5bf03b521435b4583728b6d15a660"
application_url = "https://lucky-serenity-production-2d99.up.railway.app"
embedded = true
name = "GenieStock"
handle = "geniestock"

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers"
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://lucky-serenity-production-2d99.up.railway.app/auth" ]
