import { authenticate } from "../shopify.server";
import { hasFeature } from "../services/billing.server";
import { generateCsv } from "../services/reports.server";
import prisma from "../db.server";

export const loader = async ({ request }) => {
  const { session } = await authenticate.admin(request);
  const store = await prisma.store.findUnique({ where: { shop: session.shop } });

  if (!store || !hasFeature(store.plan, "reports")) {
    return new Response("Upgrade to Pro to access reports", { status: 403 });
  }

  const format = new URL(request.url).searchParams.get("format") || "csv";

  const entries = await prisma.deadStockEntry.findMany({
    where: { shop: session.shop },
    include: { product: true },
    orderBy: { flaggedAt: "desc" },
  });

  if (format === "csv") {
    const csv = generateCsv(entries);
    return new Response(csv, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": 'attachment; filename="deadstock-report.csv"',
      },
    });
  }

  if (format === "pdf") {
    const PDFDocument = (await import("pdfkit")).default;
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const buffers = [];
    doc.on("data", (chunk) => buffers.push(chunk));

    doc.fontSize(20).text("Dead Stock Finder Report", { align: "center" });
    doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString()} | Shop: ${session.shop}`, { align: "center" });
    doc.moveDown(1.5);

    const active = entries.filter(e => !e.resolved).length;
    const resolved = entries.filter(e => e.resolved).length;
    doc.fontSize(12).text(`Summary: ${active} active, ${resolved} resolved, ${entries.length} total`);
    doc.moveDown(1);

    const colWidths = [160, 60, 60, 50, 120];
    const tableHeaders = ["Product", "Price", "Days", "Status", "Action"];
    let x = 40;
    doc.fontSize(9).font("Helvetica-Bold");
    tableHeaders.forEach((h, i) => {
      doc.text(h, x, doc.y, { width: colWidths[i], align: "left" });
      x += colWidths[i];
    });
    doc.moveDown(0.3);
    doc.moveTo(40, doc.y).lineTo(40 + colWidths.reduce((a, b) => a + b, 0), doc.y).stroke();
    doc.moveDown(0.3);

    doc.font("Helvetica").fontSize(8);
    for (const entry of entries) {
      if (doc.y > 730) {
        doc.addPage();
      }
      x = 40;
      const row = [
        entry.product.title.substring(0, 30),
        `$${entry.product.price.toFixed(2)}`,
        `${entry.daysSinceSale}d`,
        entry.resolved ? "Resolved" : "Active",
        entry.suggestedAction,
      ];
      row.forEach((val, i) => {
        doc.text(val, x, doc.y, { width: colWidths[i], align: "left" });
        x += colWidths[i];
      });
      doc.moveDown(0.5);
    }

    const totalValue = entries.reduce((sum, e) => sum + (e.product.price * e.product.inventoryCount), 0);
    doc.moveDown(2);
    doc.fontSize(10).font("Helvetica-Bold").text(`Total stuck inventory value: $${totalValue.toLocaleString()}`);
    doc.moveDown(0.5);
    doc.fontSize(8).font("Helvetica").text("Generated by Dead Stock Finder for Shopify", { align: "center" });

    const pdfDone = new Promise((resolve) => doc.on("end", resolve));
    doc.end();
    await pdfDone;

    return new Response(Buffer.concat(buffers), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="deadstock-report.pdf"',
      },
    });
  }

  return new Response("Invalid format", { status: 400 });
};
